import { Activity, ArrowRight, BookOpen, Braces, CheckCircle2, Code2, Database, FileSearch, GitBranch, GitFork, Globe2, Layers3, LockKeyhole, Moon, Network, PackageSearch, Route, ShieldCheck, Sparkles, Sun, TerminalSquare, Workflow } from 'lucide-react'

interface PageProps { theme: 'dark' | 'light'; onToggleTheme: () => void }

function InfoNav({ theme, onToggleTheme }: PageProps) {
  return <nav className="topbar info-nav">
    <a href="/" className="brand"><span className="brand-mark"><Braces size={19} /></span><span>RepoLens</span></a>
    <div className="nav-links"><a href="/">Analyzer</a><a href="/about">About</a><a href="/developers">Developers</a></div>
    <div className="home-actions"><button className="theme-toggle" type="button" onClick={onToggleTheme} aria-label={`Switch to ${theme === 'dark' ? 'light' : 'dark'} theme`}>{theme === 'dark' ? <Sun /> : <Moon />}<span>{theme === 'dark' ? 'Light' : 'Dark'}</span></button><a className="github-link" href="https://github.com/CyberGhost05" target="_blank" rel="noreferrer"><GitFork /> GitHub</a></div>
  </nav>
}

function InfoFooter() {
  return <footer><a className="brand" href="/"><span className="brand-mark"><Braces size={16} /></span>RepoLens</a><span>Built by <a href="https://github.com/CyberGhost05">Liyander Rishwanth · CyberGhost05</a></span><span>Evidence before assumptions.</span></footer>
}

export function AboutPage(props: PageProps) {
  return <div className="home-shell info-shell"><InfoNav {...props} /><main>
    <section className="info-hero"><div className="section-kicker">ABOUT REPOLENS</div><h1>Software should be easier<br />to <em>understand.</em></h1><p>RepoLens turns unfamiliar public repositories into evidence-backed maps that help developers learn systems, review changes, and find the right place to begin.</p><a className="primary-link" href="/">Analyze a repository <ArrowRight /></a></section>
    <section className="info-split"><div><div className="section-kicker">THE PROBLEM</div><h2>Repositories contain code.<br />Developers need context.</h2></div><div><p>A file tree alone does not explain where execution begins, how modules communicate, which components own data, or what a change could affect. Documentation is often incomplete, stale, or written for people who already know the system.</p><p>RepoLens builds that missing orientation layer directly from repository evidence—without cloning, installing dependencies, or executing untrusted code.</p></div></section>
    <section className="value-grid"><article><FileSearch /><span>01</span><h3>Evidence-backed</h3><p>Important conclusions point back to files, declarations, manifests, routes, and configuration found in the repository.</p></article><article><LockKeyhole /><span>02</span><h3>Safe by design</h3><p>Analysis is static and browser-based. RepoLens does not execute repository code or require access to private repositories.</p></article><article><Globe2 /><span>03</span><h3>Software-wide</h3><p>Designed for web, backend, desktop, mobile, native, embedded, data, CLI, SDK, game, and infrastructure projects.</p></article></section>
    <section className="creator-panel"><div className="creator-mark">LR</div><div><div className="section-kicker">CREATOR</div><h2>Liyander Rishwanth</h2><p>RepoLens is created by Liyander Rishwanth, also known as CyberGhost05, to shorten the distance between opening an unfamiliar repository and making a confident contribution.</p><a href="https://github.com/CyberGhost05" target="_blank" rel="noreferrer"><GitFork /> View CyberGhost05 on GitHub</a></div></section>
    <section className="info-cta"><Sparkles /><div><span>READY TO EXPLORE?</span><h2>Turn a repository into a system map.</h2></div><a href="/">Open RepoLens <ArrowRight /></a></section>
  </main><InfoFooter /></div>
}

const pipeline = [
  { icon: <GitFork />, title: 'Acquire', text: 'Read public metadata and the repository tree. If GitHub limits the request, switch automatically to the public CDN fallback.' },
  { icon: <PackageSearch />, title: 'Prioritize', text: 'Rank manifests, entry points, workflows, services, routes, models, configuration, and representative source files.' },
  { icon: <Code2 />, title: 'Analyze', text: 'Run deterministic detectors for languages, symbols, imports, endpoints, infrastructure, security boundaries, and quality signals.' },
  { icon: <Network />, title: 'Connect', text: 'Resolve local relationships into modules, component dependencies, call links, execution flows, and change-impact paths.' },
  { icon: <BookOpen />, title: 'Explain', text: 'Present the evidence as navigable architecture, onboarding guidance, health views, source explanations, and exportable reports.' },
]

export function DeveloperPage(props: PageProps) {
  return <div className="home-shell info-shell"><InfoNav {...props} /><main>
    <section className="info-hero developer-hero"><div className="section-kicker">FOR DEVELOPERS</div><h1>From repository URL<br />to <em>working context.</em></h1><p>Understand RepoLens’s acquisition pipeline, analysis boundaries, supported software, and the evidence behind each visualization.</p><div className="developer-actions"><a className="primary-link" href="/">Try the analyzer <ArrowRight /></a><a className="secondary-link" href="#pipeline">Explore the pipeline</a></div></section>
    <section className="developer-stat-row"><article><b>14</b><span>focused analysis views</span></article><article><b>3</b><span>bounded analysis depths</span></article><article><b>0</b><span>repository code executed</span></article><article><b>2</b><span>automatic acquisition paths</span></article></section>
    <section id="pipeline" className="pipeline-section"><div className="section-heading"><div><div className="section-kicker">ANALYSIS PIPELINE</div><h2>How a repository becomes a map</h2></div><p>Each stage narrows raw source into useful developer context. The analysis stays deterministic and preserves the evidence needed to review its conclusions.</p></div><div className="pipeline-list">{pipeline.map((step, index) => <article key={step.title}><div className="pipeline-number">{String(index + 1).padStart(2, '0')}</div><div className="pipeline-icon">{step.icon}</div><div><h3>{step.title}</h3><p>{step.text}</p></div>{index < pipeline.length - 1 && <i />}</article>)}</div></section>
    <section className="developer-grid"><article><Layers3 /><h3>Architecture intelligence</h3><ul><li><CheckCircle2 />Software type and platform profiling</li><li><CheckCircle2 />Module and component relationships</li><li><CheckCircle2 />Import and dependency cycles</li><li><CheckCircle2 />Architecture review signals</li></ul></article><article><Workflow /><h3>Behavior intelligence</h3><ul><li><CheckCircle2 />Startup and request flows</li><li><CheckCircle2 />Routes, handlers, and services</li><li><CheckCircle2 />Symbol callers and callees</li><li><CheckCircle2 />External system boundaries</li></ul></article><article><ShieldCheck /><h3>Change intelligence</h3><ul><li><CheckCircle2 />Impact radius exploration</li><li><CheckCircle2 />Tests related to changed source</li><li><CheckCircle2 />Complexity and hotspot signals</li><li><CheckCircle2 />Security-sensitive surfaces</li></ul></article><article><TerminalSquare /><h3>Onboarding intelligence</h3><ul><li><CheckCircle2 />Build, run, test, and lint commands</li><li><CheckCircle2 />Recommended reading order</li><li><CheckCircle2 />Entrypoints and extension points</li><li><CheckCircle2 />File-level purpose explanations</li></ul></article></section>
    <section className="fallback-panel"><div><Activity /><span>AUTOMATIC RESILIENCE</span><h2>Rate limits no longer stop the analysis.</h2><p>RepoLens first uses GitHub’s public API for live metadata, tree data, and recent commits. If that unauthenticated quota is exhausted, it automatically retrieves the public file index and prioritized source through jsDelivr. The dashboard labels the fallback and explains which live metadata may be missing.</p></div><div className="fallback-flow"><span><GitFork />GitHub API</span><i>available</i><span><Database />Live metadata + source</span><b>or</b><span><Route />Rate limited</span><i>automatic fallback</i><span><Globe2 />Public CDN source</span></div></section>
    <section className="limits-section"><div><div className="section-kicker">ANALYSIS BOUNDARIES</div><h2>What the results mean</h2></div><div><p><strong>Static evidence, not runtime certainty.</strong> Dynamic dispatch, reflection, generated code, macros, dependency injection, runtime plugins, and environment-specific behavior can create paths that source inspection cannot prove.</p><p><strong>Prioritized coverage.</strong> Quick, standard, and deep modes bound network and browser resource usage. High-signal files are inspected first; lower-priority paths remain visible in the repository index.</p><p><strong>Review signals, not vulnerability claims.</strong> Security views identify authentication, secrets handling, network boundaries, and other areas deserving human review.</p></div></section>
    <section className="info-cta"><GitBranch /><div><span>START WITH EVIDENCE</span><h2>Explore a codebase before changing it.</h2></div><a href="/">Analyze repository <ArrowRight /></a></section>
  </main><InfoFooter /></div>
}
